version: 2
jobs:
  dry-run:
    docker:
      - image: python:2.7
    steps:
      - run:
          name: Install OctoDNS
          command: pip install octodns
      - checkout
      - run:
          name: Do a dry run
          command: ./bin/dry-run
  deploy:
    docker:
      - image: python:2.7
    steps:
      - run:
          name: Install OctoDNS
          command: pip install octodns
      - checkout
      - run:
          name: Sync w/ production DNS providers
          command: ./bin/sync

workflows:
  version: 2
  dry-run-and-deploy:
    jobs:
      - dry-run
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
