---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
  dnsimple:
    class: octodns.provider.dnsimple.DnsimpleProvider
    token: env/DNSIMPLE_API_KEY
    account: env/DNSIMPLE_ACCOUNT_NUMBER
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN

zones:
  hackclub.com.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.org.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.io.:
    sources:
      - config
    targets:
      - dnsimple
  hackedu.us.:
    sources:
      - config
    targets:
      - dnsimple
  hack.af.:
    sources:
      - config
    targets:
      - cloudflare
  bulckcah.com.:
    sources:
      - config
    targets:
      - dnsimple
  hackchicago.io.:
    sources:
      - config
    targets:
      - dnsimple
